### ISSUE TITLE
Manuel detach ConnectionHose

### ISSUE THREAD

**Issue by nilBrain** [stijnwop/manualAttach#44] opened 2019-05-19 17:45 UTC
Hoses manual attaching works, but you can not detound them manually.
Only by detach of the Tool/Trailer.

**Comment by stijnwop** [comment] 2019-05-19 17:46
Not sure what you're trying to say here.. ?

**Comment by Philipp1998** [comment] 2019-05-19 18:31
I'll show you in a video.

https://youtu.be/rG6XrvjUO-k

1st Trailer is Vanilla: 100% works.
2nd Tool is a mod: does not show a Key to the Text in the Help Window.
3rd Trailer is a Mod (the Issues): Can not Detach the ConnectionHoses, only by Detach from the Trailer.

**Comment by stijnwop** [comment] 2019-05-19 18:50
2: Thats the input binding priority selection, because the hoses/pto key is set on low priority. (the game won't show all input bindings at the same time.)
3: Try with a vanilla vehicle.. and check if the mod has deviant parts.

**Comment by stijnwop** [comment] 2019-06-20 17:29
Any further input?

**Comment by stijnwop** [comment] 2019-07-14 18:52
Did a quick run with the vehicles from your video with the current version, couldn't reproduce anything from it.

Closing..

**Closed by stijnwop** 2019-07-14 18:52 UTC
