### ISSUE TITLE
Wrong Gamemenu?

### ISSUE THREAD

**Issue by ChaosfamilyWW** [stijnwop/manualAttach#106] opened 2021-12-01 11:25 UTC
Hey Wopster,
First of all, thank you for getting this mod in the 22s so quickly!
But could it be that you got the wrong menu? Only an admin can set on Dediserver whether he wants to use the mod or not

**Comment by stijnwop** [comment] 2021-12-01 11:29
Duplicate of #102

Fixed it here, need to check how it all works out in MP now ;)

**Closed by stijnwop** 2021-12-01 11:29 UTC
